version: '3'

services:
  gobarber-api:
    build: .
    container_name: gobarber-api
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - gobarber-postgres
      - gobarber-mongo
      - gobarber-redis
    networks:
      - gobarber-network
  gobarber-redis:
    image: bitnami/redis:latest
    container_name: gobarber-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /media/igor/Data/gobarber-redis-data:/data
    ports:
      - '6379:6379'
    networks:
      - gobarber-network
  gobarber-mongo:
    image: mongo:latest
    container_name: gobarber-mongo
    environment:
      - MONGO_INITDB_DATABASE=gobarber
    volumes:
      - ~/gobarber-mongo/data:/data/db
    ports:
      - '27017:27017'
    networks:
      - gobarber-network
  gobarber-postgres:
    image: postgres:alpine
    container_name: gobarber-postgres
    environment:
      - POSTGRES_DB=gobarber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ~/gobarber-postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - gobarber-network

volumes:
  gobarber-redis-data:

networks:
  gobarber-network:
    driver: bridge
